### ISSUE TITLE
Values below zero

### ISSUE THREAD

**Issue by phillipsar2** [tpbilton/GUSrelate#1]
My estimated GRM contains some negative values. Should those be set to zero as values below zero are meaningless?

**Comment by tpbilton** [comment]
The GRM are estimates from using a moment of methods estimator and so negative values can occur and under the correlation interpretation of relatedness (rather than the identity by decent definition), negative values essentially mean that these individuals are less related than the average relatedness of the population.

I would personally not set negative values to zero as this will likely lead to bias in downstream analysis (e.g., genomic prediction, population structure). Is there a reason why negative values could be a problem for your analysis?

**Comment by phillipsar2** [comment]
Thank you for this explanation. I don't expect negative values will be a problem in downstream analyses so I keep the values as they were estimated.

**Comment by tpbilton** [comment]
Thanks, I'll close this issue.
